### ISSUE TITLE
using feedin_pg for scenarios

### ISSUE THREAD

**Issue by elisagaudchau** [oemof/oemof_pg#20]
i need feedin timeseries for a small region in germany.
when i use feedin_pg i get nans for wind_power because there are no wind turbines in this area.
it would be nice to have an option to set the peak power to a "scenario value" or just 1 instead of taking it from energymap

**Comment by uvchik** [comment]
`feedin_pg` was an attempt to combine weather data sets and spatial defined power plants to get feed-in time series for a specific region. This class is definitely in a beta state but should work.

You can integrated a scenario database and add capacities. You have to keep in mind that some of the existing power plants might not exist any more in future scenarios. Furthermore you have to define where you want to build the new power plants.

It is a good idea to add this functionality to `feedin_pg`. It was intended to move it to the feedinlib anyway once the power plants and weather data sets are available for everyone. I think it might be an approach to combine the datasets from the [OPSD project](https://github.com/Open-Power-System-Data) with `feedin_pg` and remove the internal database. Then we can move it to the feedinlib. There we could think of an concept to integrate future scenarios.

We should keep in touch with the contributors of [OpenFred](https://github.com/open-fred) because they aim to do something similar.
